//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.live_StarMFWebServiceLatest {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PasswordRequest", Namespace="http://schemas.datacontract.org/2004/07/StarMFWebService")]
    [System.SerializableAttribute()]
    public partial class PasswordRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MemberIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PassKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MemberId {
            get {
                return this.MemberIdField;
            }
            set {
                if ((object.ReferenceEquals(this.MemberIdField, value) != true)) {
                    this.MemberIdField = value;
                    this.RaisePropertyChanged("MemberId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PassKey {
            get {
                return this.PassKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.PassKeyField, value) != true)) {
                    this.PassKeyField = value;
                    this.RaisePropertyChanged("PassKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIdField, value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://schemas.datacontract.org/2004/07/StarMFWebService")]
    [System.SerializableAttribute()]
    public partial class Response : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FillerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Filler {
            get {
                return this.FillerField;
            }
            set {
                if ((object.ReferenceEquals(this.FillerField, value) != true)) {
                    this.FillerField = value;
                    this.RaisePropertyChanged("Filler");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseString {
            get {
                return this.ResponseStringField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseStringField, value) != true)) {
                    this.ResponseStringField = value;
                    this.RaisePropertyChanged("ResponseString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MFAPIRequest", Namespace="http://schemas.datacontract.org/2004/07/StarMFWebService")]
    [System.SerializableAttribute()]
    public partial class MFAPIRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EncryptedPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FlagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string paramField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EncryptedPassword {
            get {
                return this.EncryptedPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.EncryptedPasswordField, value) != true)) {
                    this.EncryptedPasswordField = value;
                    this.RaisePropertyChanged("EncryptedPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Flag {
            get {
                return this.FlagField;
            }
            set {
                if ((object.ReferenceEquals(this.FlagField, value) != true)) {
                    this.FlagField = value;
                    this.RaisePropertyChanged("Flag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIdField, value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string param {
            get {
                return this.paramField;
            }
            set {
                if ((object.ReferenceEquals(this.paramField, value) != true)) {
                    this.paramField = value;
                    this.RaisePropertyChanged("param");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.bsestarmf.in/2016/01/", ConfigurationName="live_StarMFWebServiceLatest.IStarMFWebService")]
    public interface IStarMFWebService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bsestarmf.in/2016/01/IStarMFWebService/getPassword", ReplyAction="http://www.bsestarmf.in/2016/01/IStarMFWebService/getPasswordResponse")]
        string getPassword(string UserId, string MemberId, string Password, string PassKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bsestarmf.in/2016/01/IStarMFWebService/getPassword", ReplyAction="http://www.bsestarmf.in/2016/01/IStarMFWebService/getPasswordResponse")]
        System.Threading.Tasks.Task<string> getPasswordAsync(string UserId, string MemberId, string Password, string PassKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bsestarmf.in/2016/01/IStarMFWebService/MFAPI", ReplyAction="http://www.bsestarmf.in/2016/01/IStarMFWebService/MFAPIResponse")]
        string MFAPI(string Flag, string UserId, string EncryptedPassword, string param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bsestarmf.in/2016/01/IStarMFWebService/MFAPI", ReplyAction="http://www.bsestarmf.in/2016/01/IStarMFWebService/MFAPIResponse")]
        System.Threading.Tasks.Task<string> MFAPIAsync(string Flag, string UserId, string EncryptedPassword, string param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bsestarmf.in/2016/01/IStarMFWebService/GetPasswordMobile", ReplyAction="http://www.bsestarmf.in/2016/01/IStarMFWebService/GetPasswordMobileResponse")]
        Service.live_StarMFWebServiceLatest.Response GetPasswordMobile(Service.live_StarMFWebServiceLatest.PasswordRequest Param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bsestarmf.in/2016/01/IStarMFWebService/GetPasswordMobile", ReplyAction="http://www.bsestarmf.in/2016/01/IStarMFWebService/GetPasswordMobileResponse")]
        System.Threading.Tasks.Task<Service.live_StarMFWebServiceLatest.Response> GetPasswordMobileAsync(Service.live_StarMFWebServiceLatest.PasswordRequest Param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bsestarmf.in/2016/01/IStarMFWebService/MFAPIMobile", ReplyAction="http://www.bsestarmf.in/2016/01/IStarMFWebService/MFAPIMobileResponse")]
        Service.live_StarMFWebServiceLatest.Response MFAPIMobile(Service.live_StarMFWebServiceLatest.MFAPIRequest Param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bsestarmf.in/2016/01/IStarMFWebService/MFAPIMobile", ReplyAction="http://www.bsestarmf.in/2016/01/IStarMFWebService/MFAPIMobileResponse")]
        System.Threading.Tasks.Task<Service.live_StarMFWebServiceLatest.Response> MFAPIMobileAsync(Service.live_StarMFWebServiceLatest.MFAPIRequest Param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bsestarmf.in/2016/01/IStarMFWebService/Test", ReplyAction="http://www.bsestarmf.in/2016/01/IStarMFWebService/TestResponse")]
        string Test(string Name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bsestarmf.in/2016/01/IStarMFWebService/Test", ReplyAction="http://www.bsestarmf.in/2016/01/IStarMFWebService/TestResponse")]
        System.Threading.Tasks.Task<string> TestAsync(string Name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStarMFWebServiceChannel : Service.live_StarMFWebServiceLatest.IStarMFWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StarMFWebServiceClient : System.ServiceModel.ClientBase<Service.live_StarMFWebServiceLatest.IStarMFWebService>, Service.live_StarMFWebServiceLatest.IStarMFWebService {
        
        public StarMFWebServiceClient() {
        }
        
        public StarMFWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StarMFWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StarMFWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StarMFWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string getPassword(string UserId, string MemberId, string Password, string PassKey) {
            return base.Channel.getPassword(UserId, MemberId, Password, PassKey);
        }
        
        public System.Threading.Tasks.Task<string> getPasswordAsync(string UserId, string MemberId, string Password, string PassKey) {
            return base.Channel.getPasswordAsync(UserId, MemberId, Password, PassKey);
        }
        
        public string MFAPI(string Flag, string UserId, string EncryptedPassword, string param) {
            return base.Channel.MFAPI(Flag, UserId, EncryptedPassword, param);
        }
        
        public System.Threading.Tasks.Task<string> MFAPIAsync(string Flag, string UserId, string EncryptedPassword, string param) {
            return base.Channel.MFAPIAsync(Flag, UserId, EncryptedPassword, param);
        }
        
        public Service.live_StarMFWebServiceLatest.Response GetPasswordMobile(Service.live_StarMFWebServiceLatest.PasswordRequest Param) {
            return base.Channel.GetPasswordMobile(Param);
        }
        
        public System.Threading.Tasks.Task<Service.live_StarMFWebServiceLatest.Response> GetPasswordMobileAsync(Service.live_StarMFWebServiceLatest.PasswordRequest Param) {
            return base.Channel.GetPasswordMobileAsync(Param);
        }
        
        public Service.live_StarMFWebServiceLatest.Response MFAPIMobile(Service.live_StarMFWebServiceLatest.MFAPIRequest Param) {
            return base.Channel.MFAPIMobile(Param);
        }
        
        public System.Threading.Tasks.Task<Service.live_StarMFWebServiceLatest.Response> MFAPIMobileAsync(Service.live_StarMFWebServiceLatest.MFAPIRequest Param) {
            return base.Channel.MFAPIMobileAsync(Param);
        }
        
        public string Test(string Name) {
            return base.Channel.Test(Name);
        }
        
        public System.Threading.Tasks.Task<string> TestAsync(string Name) {
            return base.Channel.TestAsync(Name);
        }
    }
}
