//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceBusinessLayer.MFUploadServiceAdv {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://bsestarmfdemo.bseindia.com/2016/01/", ConfigurationName="MFUploadServiceAdv.IMFUploadService")]
    public interface IMFUploadService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bsestarmfdemo.bseindia.com/2016/01/IMFUploadService/getPassword", ReplyAction="http://bsestarmfdemo.bseindia.com/2016/01/IMFUploadService/getPasswordResponse")]
        string getPassword(string UserId, string MemberId, string Password, string PassKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bsestarmfdemo.bseindia.com/2016/01/IMFUploadService/getPassword", ReplyAction="http://bsestarmfdemo.bseindia.com/2016/01/IMFUploadService/getPasswordResponse")]
        System.Threading.Tasks.Task<string> getPasswordAsync(string UserId, string MemberId, string Password, string PassKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bsestarmfdemo.bseindia.com/2016/01/IMFUploadService/MFAPI", ReplyAction="http://bsestarmfdemo.bseindia.com/2016/01/IMFUploadService/MFAPIResponse")]
        string MFAPI(string Flag, string UserId, string EncryptedPassword, string param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bsestarmfdemo.bseindia.com/2016/01/IMFUploadService/MFAPI", ReplyAction="http://bsestarmfdemo.bseindia.com/2016/01/IMFUploadService/MFAPIResponse")]
        System.Threading.Tasks.Task<string> MFAPIAsync(string Flag, string UserId, string EncryptedPassword, string param);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMFUploadServiceChannel : ServiceBusinessLayer.MFUploadServiceAdv.IMFUploadService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MFUploadServiceClient : System.ServiceModel.ClientBase<ServiceBusinessLayer.MFUploadServiceAdv.IMFUploadService>, ServiceBusinessLayer.MFUploadServiceAdv.IMFUploadService {
        
        public MFUploadServiceClient() {
        }
        
        public MFUploadServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MFUploadServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MFUploadServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MFUploadServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string getPassword(string UserId, string MemberId, string Password, string PassKey) {
            return base.Channel.getPassword(UserId, MemberId, Password, PassKey);
        }
        
        public System.Threading.Tasks.Task<string> getPasswordAsync(string UserId, string MemberId, string Password, string PassKey) {
            return base.Channel.getPasswordAsync(UserId, MemberId, Password, PassKey);
        }
        
        public string MFAPI(string Flag, string UserId, string EncryptedPassword, string param) {
            return base.Channel.MFAPI(Flag, UserId, EncryptedPassword, param);
        }
        
        public System.Threading.Tasks.Task<string> MFAPIAsync(string Flag, string UserId, string EncryptedPassword, string param) {
            return base.Channel.MFAPIAsync(Flag, UserId, EncryptedPassword, param);
        }
    }
}
